name: CI/CD Pipeline

on:
  push:
    branches: [ master ]

  continuous-deployment:
    runs-on: ubuntu-latest
    #needs: [continuous-integration]
    if: github.ref == 'refs/heads/master'
    
    steps:
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 1
        env:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Check out code
        uses: actions/checkout@v2
    
      - name: Create docker images
        run: docker build -t 107164280007.dkr.ecr.eu-west-1.amazonaws.com/omer-test:latest .

      - name: Upload docker into ECR
        run: docker push 107164280007.dkr.ecr.eu-west-1.amazonaws.com/omer-test:latest
